package com.example.p2p.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class ApprovalStepApproverExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public ApprovalStepApproverExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApprovalStepApproverIdIsNull() {
            addCriterion("approval_step_approver_id is null");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdIsNotNull() {
            addCriterion("approval_step_approver_id is not null");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdEqualTo(String value) {
            addCriterion("approval_step_approver_id =", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdNotEqualTo(String value) {
            addCriterion("approval_step_approver_id <>", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdGreaterThan(String value) {
            addCriterion("approval_step_approver_id >", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdGreaterThanOrEqualTo(String value) {
            addCriterion("approval_step_approver_id >=", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdLessThan(String value) {
            addCriterion("approval_step_approver_id <", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdLessThanOrEqualTo(String value) {
            addCriterion("approval_step_approver_id <=", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdLike(String value) {
            addCriterion("approval_step_approver_id like", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdNotLike(String value) {
            addCriterion("approval_step_approver_id not like", value, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdIn(List<String> values) {
            addCriterion("approval_step_approver_id in", values, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdNotIn(List<String> values) {
            addCriterion("approval_step_approver_id not in", values, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdBetween(String value1, String value2) {
            addCriterion("approval_step_approver_id between", value1, value2, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepApproverIdNotBetween(String value1, String value2) {
            addCriterion("approval_step_approver_id not between", value1, value2, "approvalStepApproverId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdIsNull() {
            addCriterion("approval_step_id is null");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdIsNotNull() {
            addCriterion("approval_step_id is not null");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdEqualTo(String value) {
            addCriterion("approval_step_id =", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdNotEqualTo(String value) {
            addCriterion("approval_step_id <>", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdGreaterThan(String value) {
            addCriterion("approval_step_id >", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdGreaterThanOrEqualTo(String value) {
            addCriterion("approval_step_id >=", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdLessThan(String value) {
            addCriterion("approval_step_id <", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdLessThanOrEqualTo(String value) {
            addCriterion("approval_step_id <=", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdLike(String value) {
            addCriterion("approval_step_id like", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdNotLike(String value) {
            addCriterion("approval_step_id not like", value, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdIn(List<String> values) {
            addCriterion("approval_step_id in", values, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdNotIn(List<String> values) {
            addCriterion("approval_step_id not in", values, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdBetween(String value1, String value2) {
            addCriterion("approval_step_id between", value1, value2, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andApprovalStepIdNotBetween(String value1, String value2) {
            addCriterion("approval_step_id not between", value1, value2, "approvalStepId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAmountMinIsNull() {
            addCriterion("amount_min is null");
            return (Criteria) this;
        }

        public Criteria andAmountMinIsNotNull() {
            addCriterion("amount_min is not null");
            return (Criteria) this;
        }

        public Criteria andAmountMinEqualTo(Integer value) {
            addCriterion("amount_min =", value, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinNotEqualTo(Integer value) {
            addCriterion("amount_min <>", value, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinGreaterThan(Integer value) {
            addCriterion("amount_min >", value, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount_min >=", value, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinLessThan(Integer value) {
            addCriterion("amount_min <", value, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinLessThanOrEqualTo(Integer value) {
            addCriterion("amount_min <=", value, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinIn(List<Integer> values) {
            addCriterion("amount_min in", values, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinNotIn(List<Integer> values) {
            addCriterion("amount_min not in", values, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinBetween(Integer value1, Integer value2) {
            addCriterion("amount_min between", value1, value2, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMinNotBetween(Integer value1, Integer value2) {
            addCriterion("amount_min not between", value1, value2, "amountMin");
            return (Criteria) this;
        }

        public Criteria andAmountMaxIsNull() {
            addCriterion("amount_max is null");
            return (Criteria) this;
        }

        public Criteria andAmountMaxIsNotNull() {
            addCriterion("amount_max is not null");
            return (Criteria) this;
        }

        public Criteria andAmountMaxEqualTo(Integer value) {
            addCriterion("amount_max =", value, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxNotEqualTo(Integer value) {
            addCriterion("amount_max <>", value, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxGreaterThan(Integer value) {
            addCriterion("amount_max >", value, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount_max >=", value, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxLessThan(Integer value) {
            addCriterion("amount_max <", value, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxLessThanOrEqualTo(Integer value) {
            addCriterion("amount_max <=", value, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxIn(List<Integer> values) {
            addCriterion("amount_max in", values, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxNotIn(List<Integer> values) {
            addCriterion("amount_max not in", values, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxBetween(Integer value1, Integer value2) {
            addCriterion("amount_max between", value1, value2, "amountMax");
            return (Criteria) this;
        }

        public Criteria andAmountMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("amount_max not between", value1, value2, "amountMax");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table approval_step_approver
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 19 21:46:11 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table approval_step_approver
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}