package com.example.p2p.entity;

import com.example.p2p.enums.DocumentType;
import java.time.LocalDateTime;

public class ApprovalWorkflow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_workflow.approval_workflow_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private String approvalWorkflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_workflow.document_type
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private DocumentType documentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_workflow.created_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_workflow.updated_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_workflow.approval_workflow_id
     *
     * @return the value of approval_workflow.approval_workflow_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getApprovalWorkflowId() {
        return approvalWorkflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_workflow.approval_workflow_id
     *
     * @param approvalWorkflowId the value for approval_workflow.approval_workflow_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setApprovalWorkflowId(String approvalWorkflowId) {
        this.approvalWorkflowId = approvalWorkflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_workflow.document_type
     *
     * @return the value of approval_workflow.document_type
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public DocumentType getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_workflow.document_type
     *
     * @param documentType the value for approval_workflow.document_type
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_workflow.created_at
     *
     * @return the value of approval_workflow.created_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_workflow.created_at
     *
     * @param createdAt the value for approval_workflow.created_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_workflow.updated_at
     *
     * @return the value of approval_workflow.updated_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_workflow.updated_at
     *
     * @param updatedAt the value for approval_workflow.updated_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}