package com.example.p2p.entity;

import com.example.p2p.enums.ApprovalStatus;
import com.example.p2p.enums.DocumentType;
import java.time.LocalDateTime;

public class ApprovalTask extends ApprovalTaskKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.document_type
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private DocumentType documentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.status
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private ApprovalStatus status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.comment
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.created_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.updated_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.step_name
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private String stepName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_task.acted_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private LocalDateTime actedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.document_type
     *
     * @return the value of approval_task.document_type
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public DocumentType getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.document_type
     *
     * @param documentType the value for approval_task.document_type
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.status
     *
     * @return the value of approval_task.status
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public ApprovalStatus getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.status
     *
     * @param status the value for approval_task.status
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setStatus(ApprovalStatus status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.comment
     *
     * @return the value of approval_task.comment
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.comment
     *
     * @param comment the value for approval_task.comment
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.created_at
     *
     * @return the value of approval_task.created_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.created_at
     *
     * @param createdAt the value for approval_task.created_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.updated_at
     *
     * @return the value of approval_task.updated_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.updated_at
     *
     * @param updatedAt the value for approval_task.updated_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.step_name
     *
     * @return the value of approval_task.step_name
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public String getStepName() {
        return stepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.step_name
     *
     * @param stepName the value for approval_task.step_name
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_task.acted_at
     *
     * @return the value of approval_task.acted_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public LocalDateTime getActedAt() {
        return actedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_task.acted_at
     *
     * @param actedAt the value for approval_task.acted_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setActedAt(LocalDateTime actedAt) {
        this.actedAt = actedAt;
    }
}