package com.example.p2p.entity;

import java.time.LocalDateTime;

public class ApprovalStepApprover {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.approval_step_approver_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private String approvalStepApproverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.approval_step_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private String approvalStepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.user_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.amount_min
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private Integer amountMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.amount_max
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private Integer amountMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.created_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step_approver.updated_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.approval_step_approver_id
     *
     * @return the value of approval_step_approver.approval_step_approver_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getApprovalStepApproverId() {
        return approvalStepApproverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.approval_step_approver_id
     *
     * @param approvalStepApproverId the value for approval_step_approver.approval_step_approver_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setApprovalStepApproverId(String approvalStepApproverId) {
        this.approvalStepApproverId = approvalStepApproverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.approval_step_id
     *
     * @return the value of approval_step_approver.approval_step_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getApprovalStepId() {
        return approvalStepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.approval_step_id
     *
     * @param approvalStepId the value for approval_step_approver.approval_step_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setApprovalStepId(String approvalStepId) {
        this.approvalStepId = approvalStepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.user_id
     *
     * @return the value of approval_step_approver.user_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.user_id
     *
     * @param userId the value for approval_step_approver.user_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.amount_min
     *
     * @return the value of approval_step_approver.amount_min
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public Integer getAmountMin() {
        return amountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.amount_min
     *
     * @param amountMin the value for approval_step_approver.amount_min
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setAmountMin(Integer amountMin) {
        this.amountMin = amountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.amount_max
     *
     * @return the value of approval_step_approver.amount_max
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public Integer getAmountMax() {
        return amountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.amount_max
     *
     * @param amountMax the value for approval_step_approver.amount_max
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setAmountMax(Integer amountMax) {
        this.amountMax = amountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.created_at
     *
     * @return the value of approval_step_approver.created_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.created_at
     *
     * @param createdAt the value for approval_step_approver.created_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step_approver.updated_at
     *
     * @return the value of approval_step_approver.updated_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step_approver.updated_at
     *
     * @param updatedAt the value for approval_step_approver.updated_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}