package com.example.p2p.entity;

import java.time.LocalDateTime;

public class ApprovalStep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step.approval_step_id
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private String approvalStepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step.approval_workflow_id
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private String approvalWorkflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step.name
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step.step_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private Integer stepOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step.created_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_step.updated_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step.approval_step_id
     *
     * @return the value of approval_step.approval_step_id
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public String getApprovalStepId() {
        return approvalStepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step.approval_step_id
     *
     * @param approvalStepId the value for approval_step.approval_step_id
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setApprovalStepId(String approvalStepId) {
        this.approvalStepId = approvalStepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step.approval_workflow_id
     *
     * @return the value of approval_step.approval_workflow_id
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public String getApprovalWorkflowId() {
        return approvalWorkflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step.approval_workflow_id
     *
     * @param approvalWorkflowId the value for approval_step.approval_workflow_id
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setApprovalWorkflowId(String approvalWorkflowId) {
        this.approvalWorkflowId = approvalWorkflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step.name
     *
     * @return the value of approval_step.name
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step.name
     *
     * @param name the value for approval_step.name
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step.step_order
     *
     * @return the value of approval_step.step_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public Integer getStepOrder() {
        return stepOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step.step_order
     *
     * @param stepOrder the value for approval_step.step_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setStepOrder(Integer stepOrder) {
        this.stepOrder = stepOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step.created_at
     *
     * @return the value of approval_step.created_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step.created_at
     *
     * @param createdAt the value for approval_step.created_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval_step.updated_at
     *
     * @return the value of approval_step.updated_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval_step.updated_at
     *
     * @param updatedAt the value for approval_step.updated_at
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}