package com.example.p2p.entity;

import com.example.p2p.enums.ItemKind;
import java.time.LocalDateTime;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.kind
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private ItemKind kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.unit_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.supplier_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.description
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.is_active
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.created_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.updated_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_id
     *
     * @return the value of item.item_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_id
     *
     * @param itemId the value for item.item_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.kind
     *
     * @return the value of item.kind
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public ItemKind getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.kind
     *
     * @param kind the value for item.kind
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setKind(ItemKind kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.unit_id
     *
     * @return the value of item.unit_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.unit_id
     *
     * @param unitId the value for item.unit_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.supplier_id
     *
     * @return the value of item.supplier_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.supplier_id
     *
     * @param supplierId the value for item.supplier_id
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.description
     *
     * @return the value of item.description
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.description
     *
     * @param description the value for item.description
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.is_active
     *
     * @return the value of item.is_active
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.is_active
     *
     * @param isActive the value for item.is_active
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.created_at
     *
     * @return the value of item.created_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.created_at
     *
     * @param createdAt the value for item.created_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.updated_at
     *
     * @return the value of item.updated_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.updated_at
     *
     * @param updatedAt the value for item.updated_at
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}