package com.example.p2p.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class PurchaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.pr_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.display_number
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private Integer displayNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.requester_user_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String requesterUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.due_date
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private LocalDate dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.total_amount_excluding_tax
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private Integer totalAmountExcludingTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.status
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.created_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.updated_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.note
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.pr_id
     *
     * @return the value of purchase_request.pr_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.pr_id
     *
     * @param prId the value for purchase_request.pr_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setPrId(String prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.display_number
     *
     * @return the value of purchase_request.display_number
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public Integer getDisplayNumber() {
        return displayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.display_number
     *
     * @param displayNumber the value for purchase_request.display_number
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setDisplayNumber(Integer displayNumber) {
        this.displayNumber = displayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.requester_user_id
     *
     * @return the value of purchase_request.requester_user_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getRequesterUserId() {
        return requesterUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.requester_user_id
     *
     * @param requesterUserId the value for purchase_request.requester_user_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setRequesterUserId(String requesterUserId) {
        this.requesterUserId = requesterUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.due_date
     *
     * @return the value of purchase_request.due_date
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.due_date
     *
     * @param dueDate the value for purchase_request.due_date
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.total_amount_excluding_tax
     *
     * @return the value of purchase_request.total_amount_excluding_tax
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public Integer getTotalAmountExcludingTax() {
        return totalAmountExcludingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.total_amount_excluding_tax
     *
     * @param totalAmountExcludingTax the value for purchase_request.total_amount_excluding_tax
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setTotalAmountExcludingTax(Integer totalAmountExcludingTax) {
        this.totalAmountExcludingTax = totalAmountExcludingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.status
     *
     * @return the value of purchase_request.status
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.status
     *
     * @param status the value for purchase_request.status
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.created_at
     *
     * @return the value of purchase_request.created_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.created_at
     *
     * @param createdAt the value for purchase_request.created_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.updated_at
     *
     * @return the value of purchase_request.updated_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.updated_at
     *
     * @param updatedAt the value for purchase_request.updated_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.note
     *
     * @return the value of purchase_request.note
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.note
     *
     * @param note the value for purchase_request.note
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setNote(String note) {
        this.note = note;
    }
}