package com.example.p2p.entity;

import com.example.p2p.enums.PurchaseOrderStatus;
import com.example.p2p.enums.PurchaseOrderType;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class PurchaseOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.po_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String poId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.display_number
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private Integer displayNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.order_type
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private PurchaseOrderType orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.purchaser_user_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String purchaserUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.delivery_due_date
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private LocalDate deliveryDueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.supplier_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.snap_supplier_name
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String snapSupplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.total_amount_excluding_tax
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private Integer totalAmountExcludingTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.status
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private PurchaseOrderStatus status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.current_step_order
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private Integer currentStepOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.note
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.created_at
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.updated_at
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.service_period_from
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private LocalDate servicePeriodFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.service_period_to
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private LocalDate servicePeriodTo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.po_id
     *
     * @return the value of purchase_order.po_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getPoId() {
        return poId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.po_id
     *
     * @param poId the value for purchase_order.po_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setPoId(String poId) {
        this.poId = poId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.display_number
     *
     * @return the value of purchase_order.display_number
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public Integer getDisplayNumber() {
        return displayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.display_number
     *
     * @param displayNumber the value for purchase_order.display_number
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setDisplayNumber(Integer displayNumber) {
        this.displayNumber = displayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.order_type
     *
     * @return the value of purchase_order.order_type
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public PurchaseOrderType getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.order_type
     *
     * @param orderType the value for purchase_order.order_type
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setOrderType(PurchaseOrderType orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.purchaser_user_id
     *
     * @return the value of purchase_order.purchaser_user_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getPurchaserUserId() {
        return purchaserUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.purchaser_user_id
     *
     * @param purchaserUserId the value for purchase_order.purchaser_user_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setPurchaserUserId(String purchaserUserId) {
        this.purchaserUserId = purchaserUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.delivery_due_date
     *
     * @return the value of purchase_order.delivery_due_date
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public LocalDate getDeliveryDueDate() {
        return deliveryDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.delivery_due_date
     *
     * @param deliveryDueDate the value for purchase_order.delivery_due_date
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setDeliveryDueDate(LocalDate deliveryDueDate) {
        this.deliveryDueDate = deliveryDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.supplier_id
     *
     * @return the value of purchase_order.supplier_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.supplier_id
     *
     * @param supplierId the value for purchase_order.supplier_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.snap_supplier_name
     *
     * @return the value of purchase_order.snap_supplier_name
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getSnapSupplierName() {
        return snapSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.snap_supplier_name
     *
     * @param snapSupplierName the value for purchase_order.snap_supplier_name
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setSnapSupplierName(String snapSupplierName) {
        this.snapSupplierName = snapSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.total_amount_excluding_tax
     *
     * @return the value of purchase_order.total_amount_excluding_tax
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public Integer getTotalAmountExcludingTax() {
        return totalAmountExcludingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.total_amount_excluding_tax
     *
     * @param totalAmountExcludingTax the value for purchase_order.total_amount_excluding_tax
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setTotalAmountExcludingTax(Integer totalAmountExcludingTax) {
        this.totalAmountExcludingTax = totalAmountExcludingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.status
     *
     * @return the value of purchase_order.status
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public PurchaseOrderStatus getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.status
     *
     * @param status the value for purchase_order.status
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setStatus(PurchaseOrderStatus status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.current_step_order
     *
     * @return the value of purchase_order.current_step_order
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public Integer getCurrentStepOrder() {
        return currentStepOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.current_step_order
     *
     * @param currentStepOrder the value for purchase_order.current_step_order
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setCurrentStepOrder(Integer currentStepOrder) {
        this.currentStepOrder = currentStepOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.note
     *
     * @return the value of purchase_order.note
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.note
     *
     * @param note the value for purchase_order.note
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.created_at
     *
     * @return the value of purchase_order.created_at
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.created_at
     *
     * @param createdAt the value for purchase_order.created_at
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.updated_at
     *
     * @return the value of purchase_order.updated_at
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.updated_at
     *
     * @param updatedAt the value for purchase_order.updated_at
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.service_period_from
     *
     * @return the value of purchase_order.service_period_from
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public LocalDate getServicePeriodFrom() {
        return servicePeriodFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.service_period_from
     *
     * @param servicePeriodFrom the value for purchase_order.service_period_from
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setServicePeriodFrom(LocalDate servicePeriodFrom) {
        this.servicePeriodFrom = servicePeriodFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.service_period_to
     *
     * @return the value of purchase_order.service_period_to
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public LocalDate getServicePeriodTo() {
        return servicePeriodTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.service_period_to
     *
     * @param servicePeriodTo the value for purchase_order.service_period_to
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setServicePeriodTo(LocalDate servicePeriodTo) {
        this.servicePeriodTo = servicePeriodTo;
    }
}