package com.example.p2p.entity;

import java.time.LocalDateTime;

public class PurchaseRequestDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.pr_detail_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String prDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.pr_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.item_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.snap_item_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String snapItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.snap_kind
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String snapKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.unit_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.snap_unit_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String snapUnitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.supplier_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.snap_supplier_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private String snapSupplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.quantity
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.snap_unit_price
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private Integer snapUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.subtotal_excluding_tax
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private Integer subtotalExcludingTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.created_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.updated_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_detail.line_no
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    private Integer lineNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.pr_detail_id
     *
     * @return the value of purchase_request_detail.pr_detail_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getPrDetailId() {
        return prDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.pr_detail_id
     *
     * @param prDetailId the value for purchase_request_detail.pr_detail_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setPrDetailId(String prDetailId) {
        this.prDetailId = prDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.pr_id
     *
     * @return the value of purchase_request_detail.pr_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.pr_id
     *
     * @param prId the value for purchase_request_detail.pr_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setPrId(String prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.item_id
     *
     * @return the value of purchase_request_detail.item_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.item_id
     *
     * @param itemId the value for purchase_request_detail.item_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.snap_item_name
     *
     * @return the value of purchase_request_detail.snap_item_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getSnapItemName() {
        return snapItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.snap_item_name
     *
     * @param snapItemName the value for purchase_request_detail.snap_item_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSnapItemName(String snapItemName) {
        this.snapItemName = snapItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.snap_kind
     *
     * @return the value of purchase_request_detail.snap_kind
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getSnapKind() {
        return snapKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.snap_kind
     *
     * @param snapKind the value for purchase_request_detail.snap_kind
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSnapKind(String snapKind) {
        this.snapKind = snapKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.unit_id
     *
     * @return the value of purchase_request_detail.unit_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.unit_id
     *
     * @param unitId the value for purchase_request_detail.unit_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.snap_unit_name
     *
     * @return the value of purchase_request_detail.snap_unit_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getSnapUnitName() {
        return snapUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.snap_unit_name
     *
     * @param snapUnitName the value for purchase_request_detail.snap_unit_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSnapUnitName(String snapUnitName) {
        this.snapUnitName = snapUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.supplier_id
     *
     * @return the value of purchase_request_detail.supplier_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.supplier_id
     *
     * @param supplierId the value for purchase_request_detail.supplier_id
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.snap_supplier_name
     *
     * @return the value of purchase_request_detail.snap_supplier_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public String getSnapSupplierName() {
        return snapSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.snap_supplier_name
     *
     * @param snapSupplierName the value for purchase_request_detail.snap_supplier_name
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSnapSupplierName(String snapSupplierName) {
        this.snapSupplierName = snapSupplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.quantity
     *
     * @return the value of purchase_request_detail.quantity
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.quantity
     *
     * @param quantity the value for purchase_request_detail.quantity
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.snap_unit_price
     *
     * @return the value of purchase_request_detail.snap_unit_price
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public Integer getSnapUnitPrice() {
        return snapUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.snap_unit_price
     *
     * @param snapUnitPrice the value for purchase_request_detail.snap_unit_price
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSnapUnitPrice(Integer snapUnitPrice) {
        this.snapUnitPrice = snapUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.subtotal_excluding_tax
     *
     * @return the value of purchase_request_detail.subtotal_excluding_tax
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public Integer getSubtotalExcludingTax() {
        return subtotalExcludingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.subtotal_excluding_tax
     *
     * @param subtotalExcludingTax the value for purchase_request_detail.subtotal_excluding_tax
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setSubtotalExcludingTax(Integer subtotalExcludingTax) {
        this.subtotalExcludingTax = subtotalExcludingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.created_at
     *
     * @return the value of purchase_request_detail.created_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.created_at
     *
     * @param createdAt the value for purchase_request_detail.created_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.updated_at
     *
     * @return the value of purchase_request_detail.updated_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.updated_at
     *
     * @param updatedAt the value for purchase_request_detail.updated_at
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_detail.line_no
     *
     * @return the value of purchase_request_detail.line_no
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public Integer getLineNo() {
        return lineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_detail.line_no
     *
     * @param lineNo the value for purchase_request_detail.line_no
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    public void setLineNo(Integer lineNo) {
        this.lineNo = lineNo;
    }
}