package com.example.p2p.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class PurchaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.pr_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.display_number
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private Integer displayNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.supplier_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.requester_user_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String requesterUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.due_date
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private LocalDate dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.total_amount
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private Integer totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.status
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.created_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request.updated_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.pr_id
     *
     * @return the value of purchase_request.pr_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.pr_id
     *
     * @param prId the value for purchase_request.pr_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setPrId(String prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.display_number
     *
     * @return the value of purchase_request.display_number
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public Integer getDisplayNumber() {
        return displayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.display_number
     *
     * @param displayNumber the value for purchase_request.display_number
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setDisplayNumber(Integer displayNumber) {
        this.displayNumber = displayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.supplier_id
     *
     * @return the value of purchase_request.supplier_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.supplier_id
     *
     * @param supplierId the value for purchase_request.supplier_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.requester_user_id
     *
     * @return the value of purchase_request.requester_user_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getRequesterUserId() {
        return requesterUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.requester_user_id
     *
     * @param requesterUserId the value for purchase_request.requester_user_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setRequesterUserId(String requesterUserId) {
        this.requesterUserId = requesterUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.due_date
     *
     * @return the value of purchase_request.due_date
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.due_date
     *
     * @param dueDate the value for purchase_request.due_date
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.total_amount
     *
     * @return the value of purchase_request.total_amount
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public Integer getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.total_amount
     *
     * @param totalAmount the value for purchase_request.total_amount
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.status
     *
     * @return the value of purchase_request.status
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.status
     *
     * @param status the value for purchase_request.status
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.created_at
     *
     * @return the value of purchase_request.created_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.created_at
     *
     * @param createdAt the value for purchase_request.created_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request.updated_at
     *
     * @return the value of purchase_request.updated_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request.updated_at
     *
     * @param updatedAt the value for purchase_request.updated_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}