package com.example.p2p.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PurchaseOrderLineAllocationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public PurchaseOrderLineAllocationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrDetailIdIsNull() {
            addCriterion("pr_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdIsNotNull() {
            addCriterion("pr_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdEqualTo(String value) {
            addCriterion("pr_detail_id =", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotEqualTo(String value) {
            addCriterion("pr_detail_id <>", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdGreaterThan(String value) {
            addCriterion("pr_detail_id >", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdGreaterThanOrEqualTo(String value) {
            addCriterion("pr_detail_id >=", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdLessThan(String value) {
            addCriterion("pr_detail_id <", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdLessThanOrEqualTo(String value) {
            addCriterion("pr_detail_id <=", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdLike(String value) {
            addCriterion("pr_detail_id like", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotLike(String value) {
            addCriterion("pr_detail_id not like", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdIn(List<String> values) {
            addCriterion("pr_detail_id in", values, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotIn(List<String> values) {
            addCriterion("pr_detail_id not in", values, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdBetween(String value1, String value2) {
            addCriterion("pr_detail_id between", value1, value2, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotBetween(String value1, String value2) {
            addCriterion("pr_detail_id not between", value1, value2, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdIsNull() {
            addCriterion("po_line_id is null");
            return (Criteria) this;
        }

        public Criteria andPoLineIdIsNotNull() {
            addCriterion("po_line_id is not null");
            return (Criteria) this;
        }

        public Criteria andPoLineIdEqualTo(String value) {
            addCriterion("po_line_id =", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdNotEqualTo(String value) {
            addCriterion("po_line_id <>", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdGreaterThan(String value) {
            addCriterion("po_line_id >", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdGreaterThanOrEqualTo(String value) {
            addCriterion("po_line_id >=", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdLessThan(String value) {
            addCriterion("po_line_id <", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdLessThanOrEqualTo(String value) {
            addCriterion("po_line_id <=", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdLike(String value) {
            addCriterion("po_line_id like", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdNotLike(String value) {
            addCriterion("po_line_id not like", value, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdIn(List<String> values) {
            addCriterion("po_line_id in", values, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdNotIn(List<String> values) {
            addCriterion("po_line_id not in", values, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdBetween(String value1, String value2) {
            addCriterion("po_line_id between", value1, value2, "poLineId");
            return (Criteria) this;
        }

        public Criteria andPoLineIdNotBetween(String value1, String value2) {
            addCriterion("po_line_id not between", value1, value2, "poLineId");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityIsNull() {
            addCriterion("allocated_quantity is null");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityIsNotNull() {
            addCriterion("allocated_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityEqualTo(Integer value) {
            addCriterion("allocated_quantity =", value, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityNotEqualTo(Integer value) {
            addCriterion("allocated_quantity <>", value, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityGreaterThan(Integer value) {
            addCriterion("allocated_quantity >", value, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("allocated_quantity >=", value, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityLessThan(Integer value) {
            addCriterion("allocated_quantity <", value, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("allocated_quantity <=", value, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityIn(List<Integer> values) {
            addCriterion("allocated_quantity in", values, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityNotIn(List<Integer> values) {
            addCriterion("allocated_quantity not in", values, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityBetween(Integer value1, Integer value2) {
            addCriterion("allocated_quantity between", value1, value2, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andAllocatedQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("allocated_quantity not between", value1, value2, "allocatedQuantity");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 18 16:56:03 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}