package com.example.p2p.entity;

public class PurchaseOrderLineAllocationKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_line_allocation.pr_detail_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private String prDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_line_allocation.po_line_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private String poLineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_line_allocation.pr_detail_id
     *
     * @return the value of purchase_order_line_allocation.pr_detail_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getPrDetailId() {
        return prDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_line_allocation.pr_detail_id
     *
     * @param prDetailId the value for purchase_order_line_allocation.pr_detail_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setPrDetailId(String prDetailId) {
        this.prDetailId = prDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_line_allocation.po_line_id
     *
     * @return the value of purchase_order_line_allocation.po_line_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getPoLineId() {
        return poLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_line_allocation.po_line_id
     *
     * @param poLineId the value for purchase_order_line_allocation.po_line_id
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setPoLineId(String poLineId) {
        this.poLineId = poLineId;
    }
}