package com.example.p2p.entity;

import java.time.LocalDateTime;

public class PurchaseRequestPurchaseOrder extends PurchaseRequestPurchaseOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_purchase_order.created_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_purchase_order.created_at
     *
     * @return the value of purchase_request_purchase_order.created_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_purchase_order.created_at
     *
     * @param createdAt the value for purchase_request_purchase_order.created_at
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}