package com.example.p2p.entity;

public class PurchaseRequestPurchaseOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_purchase_order.pr_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String prId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_request_purchase_order.po_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    private String poId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_purchase_order.pr_id
     *
     * @return the value of purchase_request_purchase_order.pr_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getPrId() {
        return prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_purchase_order.pr_id
     *
     * @param prId the value for purchase_request_purchase_order.pr_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setPrId(String prId) {
        this.prId = prId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_request_purchase_order.po_id
     *
     * @return the value of purchase_request_purchase_order.po_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public String getPoId() {
        return poId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_request_purchase_order.po_id
     *
     * @param poId the value for purchase_request_purchase_order.po_id
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    public void setPoId(String poId) {
        this.poId = poId;
    }
}