package com.example.p2p.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PurchaseRequestDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public PurchaseRequestDetailExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrDetailIdIsNull() {
            addCriterion("pr_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdIsNotNull() {
            addCriterion("pr_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdEqualTo(String value) {
            addCriterion("pr_detail_id =", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotEqualTo(String value) {
            addCriterion("pr_detail_id <>", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdGreaterThan(String value) {
            addCriterion("pr_detail_id >", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdGreaterThanOrEqualTo(String value) {
            addCriterion("pr_detail_id >=", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdLessThan(String value) {
            addCriterion("pr_detail_id <", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdLessThanOrEqualTo(String value) {
            addCriterion("pr_detail_id <=", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdLike(String value) {
            addCriterion("pr_detail_id like", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotLike(String value) {
            addCriterion("pr_detail_id not like", value, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdIn(List<String> values) {
            addCriterion("pr_detail_id in", values, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotIn(List<String> values) {
            addCriterion("pr_detail_id not in", values, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdBetween(String value1, String value2) {
            addCriterion("pr_detail_id between", value1, value2, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrDetailIdNotBetween(String value1, String value2) {
            addCriterion("pr_detail_id not between", value1, value2, "prDetailId");
            return (Criteria) this;
        }

        public Criteria andPrIdIsNull() {
            addCriterion("pr_id is null");
            return (Criteria) this;
        }

        public Criteria andPrIdIsNotNull() {
            addCriterion("pr_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrIdEqualTo(String value) {
            addCriterion("pr_id =", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdNotEqualTo(String value) {
            addCriterion("pr_id <>", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdGreaterThan(String value) {
            addCriterion("pr_id >", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdGreaterThanOrEqualTo(String value) {
            addCriterion("pr_id >=", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdLessThan(String value) {
            addCriterion("pr_id <", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdLessThanOrEqualTo(String value) {
            addCriterion("pr_id <=", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdLike(String value) {
            addCriterion("pr_id like", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdNotLike(String value) {
            addCriterion("pr_id not like", value, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdIn(List<String> values) {
            addCriterion("pr_id in", values, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdNotIn(List<String> values) {
            addCriterion("pr_id not in", values, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdBetween(String value1, String value2) {
            addCriterion("pr_id between", value1, value2, "prId");
            return (Criteria) this;
        }

        public Criteria andPrIdNotBetween(String value1, String value2) {
            addCriterion("pr_id not between", value1, value2, "prId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameIsNull() {
            addCriterion("snap_item_name is null");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameIsNotNull() {
            addCriterion("snap_item_name is not null");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameEqualTo(String value) {
            addCriterion("snap_item_name =", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameNotEqualTo(String value) {
            addCriterion("snap_item_name <>", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameGreaterThan(String value) {
            addCriterion("snap_item_name >", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("snap_item_name >=", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameLessThan(String value) {
            addCriterion("snap_item_name <", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameLessThanOrEqualTo(String value) {
            addCriterion("snap_item_name <=", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameLike(String value) {
            addCriterion("snap_item_name like", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameNotLike(String value) {
            addCriterion("snap_item_name not like", value, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameIn(List<String> values) {
            addCriterion("snap_item_name in", values, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameNotIn(List<String> values) {
            addCriterion("snap_item_name not in", values, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameBetween(String value1, String value2) {
            addCriterion("snap_item_name between", value1, value2, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapItemNameNotBetween(String value1, String value2) {
            addCriterion("snap_item_name not between", value1, value2, "snapItemName");
            return (Criteria) this;
        }

        public Criteria andSnapKindIsNull() {
            addCriterion("snap_kind is null");
            return (Criteria) this;
        }

        public Criteria andSnapKindIsNotNull() {
            addCriterion("snap_kind is not null");
            return (Criteria) this;
        }

        public Criteria andSnapKindEqualTo(String value) {
            addCriterion("snap_kind =", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindNotEqualTo(String value) {
            addCriterion("snap_kind <>", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindGreaterThan(String value) {
            addCriterion("snap_kind >", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindGreaterThanOrEqualTo(String value) {
            addCriterion("snap_kind >=", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindLessThan(String value) {
            addCriterion("snap_kind <", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindLessThanOrEqualTo(String value) {
            addCriterion("snap_kind <=", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindLike(String value) {
            addCriterion("snap_kind like", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindNotLike(String value) {
            addCriterion("snap_kind not like", value, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindIn(List<String> values) {
            addCriterion("snap_kind in", values, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindNotIn(List<String> values) {
            addCriterion("snap_kind not in", values, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindBetween(String value1, String value2) {
            addCriterion("snap_kind between", value1, value2, "snapKind");
            return (Criteria) this;
        }

        public Criteria andSnapKindNotBetween(String value1, String value2) {
            addCriterion("snap_kind not between", value1, value2, "snapKind");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNull() {
            addCriterion("unit_id is null");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNotNull() {
            addCriterion("unit_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnitIdEqualTo(String value) {
            addCriterion("unit_id =", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotEqualTo(String value) {
            addCriterion("unit_id <>", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThan(String value) {
            addCriterion("unit_id >", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThanOrEqualTo(String value) {
            addCriterion("unit_id >=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThan(String value) {
            addCriterion("unit_id <", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThanOrEqualTo(String value) {
            addCriterion("unit_id <=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLike(String value) {
            addCriterion("unit_id like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotLike(String value) {
            addCriterion("unit_id not like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdIn(List<String> values) {
            addCriterion("unit_id in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotIn(List<String> values) {
            addCriterion("unit_id not in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdBetween(String value1, String value2) {
            addCriterion("unit_id between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotBetween(String value1, String value2) {
            addCriterion("unit_id not between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameIsNull() {
            addCriterion("snap_unit_name is null");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameIsNotNull() {
            addCriterion("snap_unit_name is not null");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameEqualTo(String value) {
            addCriterion("snap_unit_name =", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameNotEqualTo(String value) {
            addCriterion("snap_unit_name <>", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameGreaterThan(String value) {
            addCriterion("snap_unit_name >", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("snap_unit_name >=", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameLessThan(String value) {
            addCriterion("snap_unit_name <", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameLessThanOrEqualTo(String value) {
            addCriterion("snap_unit_name <=", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameLike(String value) {
            addCriterion("snap_unit_name like", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameNotLike(String value) {
            addCriterion("snap_unit_name not like", value, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameIn(List<String> values) {
            addCriterion("snap_unit_name in", values, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameNotIn(List<String> values) {
            addCriterion("snap_unit_name not in", values, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameBetween(String value1, String value2) {
            addCriterion("snap_unit_name between", value1, value2, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSnapUnitNameNotBetween(String value1, String value2) {
            addCriterion("snap_unit_name not between", value1, value2, "snapUnitName");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNull() {
            addCriterion("supplier_id is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNotNull() {
            addCriterion("supplier_id is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdEqualTo(String value) {
            addCriterion("supplier_id =", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotEqualTo(String value) {
            addCriterion("supplier_id <>", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThan(String value) {
            addCriterion("supplier_id >", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_id >=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThan(String value) {
            addCriterion("supplier_id <", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThanOrEqualTo(String value) {
            addCriterion("supplier_id <=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLike(String value) {
            addCriterion("supplier_id like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotLike(String value) {
            addCriterion("supplier_id not like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIn(List<String> values) {
            addCriterion("supplier_id in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotIn(List<String> values) {
            addCriterion("supplier_id not in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdBetween(String value1, String value2) {
            addCriterion("supplier_id between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotBetween(String value1, String value2) {
            addCriterion("supplier_id not between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameIsNull() {
            addCriterion("snap_supplier_name is null");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameIsNotNull() {
            addCriterion("snap_supplier_name is not null");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameEqualTo(String value) {
            addCriterion("snap_supplier_name =", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameNotEqualTo(String value) {
            addCriterion("snap_supplier_name <>", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameGreaterThan(String value) {
            addCriterion("snap_supplier_name >", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameGreaterThanOrEqualTo(String value) {
            addCriterion("snap_supplier_name >=", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameLessThan(String value) {
            addCriterion("snap_supplier_name <", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameLessThanOrEqualTo(String value) {
            addCriterion("snap_supplier_name <=", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameLike(String value) {
            addCriterion("snap_supplier_name like", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameNotLike(String value) {
            addCriterion("snap_supplier_name not like", value, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameIn(List<String> values) {
            addCriterion("snap_supplier_name in", values, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameNotIn(List<String> values) {
            addCriterion("snap_supplier_name not in", values, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameBetween(String value1, String value2) {
            addCriterion("snap_supplier_name between", value1, value2, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andSnapSupplierNameNotBetween(String value1, String value2) {
            addCriterion("snap_supplier_name not between", value1, value2, "snapSupplierName");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceIsNull() {
            addCriterion("snap_unit_price is null");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceIsNotNull() {
            addCriterion("snap_unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceEqualTo(Integer value) {
            addCriterion("snap_unit_price =", value, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceNotEqualTo(Integer value) {
            addCriterion("snap_unit_price <>", value, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceGreaterThan(Integer value) {
            addCriterion("snap_unit_price >", value, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("snap_unit_price >=", value, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceLessThan(Integer value) {
            addCriterion("snap_unit_price <", value, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceLessThanOrEqualTo(Integer value) {
            addCriterion("snap_unit_price <=", value, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceIn(List<Integer> values) {
            addCriterion("snap_unit_price in", values, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceNotIn(List<Integer> values) {
            addCriterion("snap_unit_price not in", values, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceBetween(Integer value1, Integer value2) {
            addCriterion("snap_unit_price between", value1, value2, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSnapUnitPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("snap_unit_price not between", value1, value2, "snapUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxIsNull() {
            addCriterion("subtotal_excluding_tax is null");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxIsNotNull() {
            addCriterion("subtotal_excluding_tax is not null");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxEqualTo(Integer value) {
            addCriterion("subtotal_excluding_tax =", value, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxNotEqualTo(Integer value) {
            addCriterion("subtotal_excluding_tax <>", value, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxGreaterThan(Integer value) {
            addCriterion("subtotal_excluding_tax >", value, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("subtotal_excluding_tax >=", value, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxLessThan(Integer value) {
            addCriterion("subtotal_excluding_tax <", value, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxLessThanOrEqualTo(Integer value) {
            addCriterion("subtotal_excluding_tax <=", value, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxIn(List<Integer> values) {
            addCriterion("subtotal_excluding_tax in", values, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxNotIn(List<Integer> values) {
            addCriterion("subtotal_excluding_tax not in", values, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxBetween(Integer value1, Integer value2) {
            addCriterion("subtotal_excluding_tax between", value1, value2, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andSubtotalExcludingTaxNotBetween(Integer value1, Integer value2) {
            addCriterion("subtotal_excluding_tax not between", value1, value2, "subtotalExcludingTax");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table purchase_request_detail
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 26 15:32:57 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}