package com.example.p2p.entity;

import com.example.p2p.enums.VisibilityScope;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public RoleExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(String value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(String value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(String value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(String value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLike(String value) {
            addCriterion("role_id like", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotLike(String value) {
            addCriterion("role_id not like", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<String> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<String> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(String value1, String value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPrCreateIsNull() {
            addCriterion("pr_create is null");
            return (Criteria) this;
        }

        public Criteria andPrCreateIsNotNull() {
            addCriterion("pr_create is not null");
            return (Criteria) this;
        }

        public Criteria andPrCreateEqualTo(Boolean value) {
            addCriterion("pr_create =", value, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateNotEqualTo(Boolean value) {
            addCriterion("pr_create <>", value, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateGreaterThan(Boolean value) {
            addCriterion("pr_create >", value, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("pr_create >=", value, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateLessThan(Boolean value) {
            addCriterion("pr_create <", value, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateLessThanOrEqualTo(Boolean value) {
            addCriterion("pr_create <=", value, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateIn(List<Boolean> values) {
            addCriterion("pr_create in", values, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateNotIn(List<Boolean> values) {
            addCriterion("pr_create not in", values, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateBetween(Boolean value1, Boolean value2) {
            addCriterion("pr_create between", value1, value2, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPrCreateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("pr_create not between", value1, value2, "prCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateIsNull() {
            addCriterion("po_create is null");
            return (Criteria) this;
        }

        public Criteria andPoCreateIsNotNull() {
            addCriterion("po_create is not null");
            return (Criteria) this;
        }

        public Criteria andPoCreateEqualTo(Boolean value) {
            addCriterion("po_create =", value, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateNotEqualTo(Boolean value) {
            addCriterion("po_create <>", value, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateGreaterThan(Boolean value) {
            addCriterion("po_create >", value, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("po_create >=", value, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateLessThan(Boolean value) {
            addCriterion("po_create <", value, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateLessThanOrEqualTo(Boolean value) {
            addCriterion("po_create <=", value, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateIn(List<Boolean> values) {
            addCriterion("po_create in", values, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateNotIn(List<Boolean> values) {
            addCriterion("po_create not in", values, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateBetween(Boolean value1, Boolean value2) {
            addCriterion("po_create between", value1, value2, "poCreate");
            return (Criteria) this;
        }

        public Criteria andPoCreateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("po_create not between", value1, value2, "poCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateIsNull() {
            addCriterion("receipt_create is null");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateIsNotNull() {
            addCriterion("receipt_create is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateEqualTo(Boolean value) {
            addCriterion("receipt_create =", value, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateNotEqualTo(Boolean value) {
            addCriterion("receipt_create <>", value, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateGreaterThan(Boolean value) {
            addCriterion("receipt_create >", value, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("receipt_create >=", value, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateLessThan(Boolean value) {
            addCriterion("receipt_create <", value, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateLessThanOrEqualTo(Boolean value) {
            addCriterion("receipt_create <=", value, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateIn(List<Boolean> values) {
            addCriterion("receipt_create in", values, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateNotIn(List<Boolean> values) {
            addCriterion("receipt_create not in", values, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateBetween(Boolean value1, Boolean value2) {
            addCriterion("receipt_create between", value1, value2, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andReceiptCreateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("receipt_create not between", value1, value2, "receiptCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateIsNull() {
            addCriterion("invoice_create is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateIsNotNull() {
            addCriterion("invoice_create is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateEqualTo(Boolean value) {
            addCriterion("invoice_create =", value, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateNotEqualTo(Boolean value) {
            addCriterion("invoice_create <>", value, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateGreaterThan(Boolean value) {
            addCriterion("invoice_create >", value, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("invoice_create >=", value, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateLessThan(Boolean value) {
            addCriterion("invoice_create <", value, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateLessThanOrEqualTo(Boolean value) {
            addCriterion("invoice_create <=", value, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateIn(List<Boolean> values) {
            addCriterion("invoice_create in", values, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateNotIn(List<Boolean> values) {
            addCriterion("invoice_create not in", values, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateBetween(Boolean value1, Boolean value2) {
            addCriterion("invoice_create between", value1, value2, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andInvoiceCreateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("invoice_create not between", value1, value2, "invoiceCreate");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeIsNull() {
            addCriterion("pr_view_scope is null");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeIsNotNull() {
            addCriterion("pr_view_scope is not null");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeEqualTo(VisibilityScope value) {
            addCriterion("pr_view_scope =", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeNotEqualTo(VisibilityScope value) {
            addCriterion("pr_view_scope <>", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeGreaterThan(VisibilityScope value) {
            addCriterion("pr_view_scope >", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeGreaterThanOrEqualTo(VisibilityScope value) {
            addCriterion("pr_view_scope >=", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeLessThan(VisibilityScope value) {
            addCriterion("pr_view_scope <", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeLessThanOrEqualTo(VisibilityScope value) {
            addCriterion("pr_view_scope <=", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeLike(VisibilityScope value) {
            addCriterion("pr_view_scope like", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeNotLike(VisibilityScope value) {
            addCriterion("pr_view_scope not like", value, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeIn(List<VisibilityScope> values) {
            addCriterion("pr_view_scope in", values, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeNotIn(List<VisibilityScope> values) {
            addCriterion("pr_view_scope not in", values, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("pr_view_scope between", value1, value2, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPrViewScopeNotBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("pr_view_scope not between", value1, value2, "prViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeIsNull() {
            addCriterion("po_view_scope is null");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeIsNotNull() {
            addCriterion("po_view_scope is not null");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeEqualTo(VisibilityScope value) {
            addCriterion("po_view_scope =", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeNotEqualTo(VisibilityScope value) {
            addCriterion("po_view_scope <>", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeGreaterThan(VisibilityScope value) {
            addCriterion("po_view_scope >", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeGreaterThanOrEqualTo(VisibilityScope value) {
            addCriterion("po_view_scope >=", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeLessThan(VisibilityScope value) {
            addCriterion("po_view_scope <", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeLessThanOrEqualTo(VisibilityScope value) {
            addCriterion("po_view_scope <=", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeLike(VisibilityScope value) {
            addCriterion("po_view_scope like", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeNotLike(VisibilityScope value) {
            addCriterion("po_view_scope not like", value, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeIn(List<VisibilityScope> values) {
            addCriterion("po_view_scope in", values, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeNotIn(List<VisibilityScope> values) {
            addCriterion("po_view_scope not in", values, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("po_view_scope between", value1, value2, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andPoViewScopeNotBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("po_view_scope not between", value1, value2, "poViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeIsNull() {
            addCriterion("receipt_view_scope is null");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeIsNotNull() {
            addCriterion("receipt_view_scope is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeEqualTo(VisibilityScope value) {
            addCriterion("receipt_view_scope =", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeNotEqualTo(VisibilityScope value) {
            addCriterion("receipt_view_scope <>", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeGreaterThan(VisibilityScope value) {
            addCriterion("receipt_view_scope >", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeGreaterThanOrEqualTo(VisibilityScope value) {
            addCriterion("receipt_view_scope >=", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeLessThan(VisibilityScope value) {
            addCriterion("receipt_view_scope <", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeLessThanOrEqualTo(VisibilityScope value) {
            addCriterion("receipt_view_scope <=", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeLike(VisibilityScope value) {
            addCriterion("receipt_view_scope like", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeNotLike(VisibilityScope value) {
            addCriterion("receipt_view_scope not like", value, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeIn(List<VisibilityScope> values) {
            addCriterion("receipt_view_scope in", values, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeNotIn(List<VisibilityScope> values) {
            addCriterion("receipt_view_scope not in", values, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("receipt_view_scope between", value1, value2, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andReceiptViewScopeNotBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("receipt_view_scope not between", value1, value2, "receiptViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeIsNull() {
            addCriterion("invoice_view_scope is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeIsNotNull() {
            addCriterion("invoice_view_scope is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeEqualTo(VisibilityScope value) {
            addCriterion("invoice_view_scope =", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeNotEqualTo(VisibilityScope value) {
            addCriterion("invoice_view_scope <>", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeGreaterThan(VisibilityScope value) {
            addCriterion("invoice_view_scope >", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeGreaterThanOrEqualTo(VisibilityScope value) {
            addCriterion("invoice_view_scope >=", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeLessThan(VisibilityScope value) {
            addCriterion("invoice_view_scope <", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeLessThanOrEqualTo(VisibilityScope value) {
            addCriterion("invoice_view_scope <=", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeLike(VisibilityScope value) {
            addCriterion("invoice_view_scope like", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeNotLike(VisibilityScope value) {
            addCriterion("invoice_view_scope not like", value, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeIn(List<VisibilityScope> values) {
            addCriterion("invoice_view_scope in", values, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeNotIn(List<VisibilityScope> values) {
            addCriterion("invoice_view_scope not in", values, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("invoice_view_scope between", value1, value2, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andInvoiceViewScopeNotBetween(VisibilityScope value1, VisibilityScope value2) {
            addCriterion("invoice_view_scope not between", value1, value2, "invoiceViewScope");
            return (Criteria) this;
        }

        public Criteria andPrApproveIsNull() {
            addCriterion("pr_approve is null");
            return (Criteria) this;
        }

        public Criteria andPrApproveIsNotNull() {
            addCriterion("pr_approve is not null");
            return (Criteria) this;
        }

        public Criteria andPrApproveEqualTo(Boolean value) {
            addCriterion("pr_approve =", value, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveNotEqualTo(Boolean value) {
            addCriterion("pr_approve <>", value, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveGreaterThan(Boolean value) {
            addCriterion("pr_approve >", value, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("pr_approve >=", value, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveLessThan(Boolean value) {
            addCriterion("pr_approve <", value, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveLessThanOrEqualTo(Boolean value) {
            addCriterion("pr_approve <=", value, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveIn(List<Boolean> values) {
            addCriterion("pr_approve in", values, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveNotIn(List<Boolean> values) {
            addCriterion("pr_approve not in", values, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveBetween(Boolean value1, Boolean value2) {
            addCriterion("pr_approve between", value1, value2, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPrApproveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("pr_approve not between", value1, value2, "prApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveIsNull() {
            addCriterion("po_approve is null");
            return (Criteria) this;
        }

        public Criteria andPoApproveIsNotNull() {
            addCriterion("po_approve is not null");
            return (Criteria) this;
        }

        public Criteria andPoApproveEqualTo(Boolean value) {
            addCriterion("po_approve =", value, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveNotEqualTo(Boolean value) {
            addCriterion("po_approve <>", value, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveGreaterThan(Boolean value) {
            addCriterion("po_approve >", value, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("po_approve >=", value, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveLessThan(Boolean value) {
            addCriterion("po_approve <", value, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveLessThanOrEqualTo(Boolean value) {
            addCriterion("po_approve <=", value, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveIn(List<Boolean> values) {
            addCriterion("po_approve in", values, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveNotIn(List<Boolean> values) {
            addCriterion("po_approve not in", values, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveBetween(Boolean value1, Boolean value2) {
            addCriterion("po_approve between", value1, value2, "poApprove");
            return (Criteria) this;
        }

        public Criteria andPoApproveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("po_approve not between", value1, value2, "poApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveIsNull() {
            addCriterion("invoice_approve is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveIsNotNull() {
            addCriterion("invoice_approve is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveEqualTo(Boolean value) {
            addCriterion("invoice_approve =", value, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveNotEqualTo(Boolean value) {
            addCriterion("invoice_approve <>", value, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveGreaterThan(Boolean value) {
            addCriterion("invoice_approve >", value, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("invoice_approve >=", value, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveLessThan(Boolean value) {
            addCriterion("invoice_approve <", value, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveLessThanOrEqualTo(Boolean value) {
            addCriterion("invoice_approve <=", value, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveIn(List<Boolean> values) {
            addCriterion("invoice_approve in", values, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveNotIn(List<Boolean> values) {
            addCriterion("invoice_approve not in", values, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveBetween(Boolean value1, Boolean value2) {
            addCriterion("invoice_approve between", value1, value2, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andInvoiceApproveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("invoice_approve not between", value1, value2, "invoiceApprove");
            return (Criteria) this;
        }

        public Criteria andSettingManageIsNull() {
            addCriterion("setting_manage is null");
            return (Criteria) this;
        }

        public Criteria andSettingManageIsNotNull() {
            addCriterion("setting_manage is not null");
            return (Criteria) this;
        }

        public Criteria andSettingManageEqualTo(Boolean value) {
            addCriterion("setting_manage =", value, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageNotEqualTo(Boolean value) {
            addCriterion("setting_manage <>", value, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageGreaterThan(Boolean value) {
            addCriterion("setting_manage >", value, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageGreaterThanOrEqualTo(Boolean value) {
            addCriterion("setting_manage >=", value, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageLessThan(Boolean value) {
            addCriterion("setting_manage <", value, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageLessThanOrEqualTo(Boolean value) {
            addCriterion("setting_manage <=", value, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageIn(List<Boolean> values) {
            addCriterion("setting_manage in", values, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageNotIn(List<Boolean> values) {
            addCriterion("setting_manage not in", values, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageBetween(Boolean value1, Boolean value2) {
            addCriterion("setting_manage between", value1, value2, "settingManage");
            return (Criteria) this;
        }

        public Criteria andSettingManageNotBetween(Boolean value1, Boolean value2) {
            addCriterion("setting_manage not between", value1, value2, "settingManage");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 18 16:56:03 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}