package com.example.p2p.entity;

import java.time.LocalDateTime;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.pr_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean prCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.po_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean poCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.receipt_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean receiptCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.invoice_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean invoiceCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.pr_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private String prViewScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.po_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private String poViewScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.receipt_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private String receiptViewScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.invoice_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private String invoiceViewScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.pr_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean prApprove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.po_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean poApprove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.invoice_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean invoiceApprove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.setting_manage
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private Boolean settingManage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.created_at
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.updated_at
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.pr_create
     *
     * @return the value of role.pr_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getPrCreate() {
        return prCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.pr_create
     *
     * @param prCreate the value for role.pr_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setPrCreate(Boolean prCreate) {
        this.prCreate = prCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.po_create
     *
     * @return the value of role.po_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getPoCreate() {
        return poCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.po_create
     *
     * @param poCreate the value for role.po_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setPoCreate(Boolean poCreate) {
        this.poCreate = poCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.receipt_create
     *
     * @return the value of role.receipt_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getReceiptCreate() {
        return receiptCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.receipt_create
     *
     * @param receiptCreate the value for role.receipt_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setReceiptCreate(Boolean receiptCreate) {
        this.receiptCreate = receiptCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.invoice_create
     *
     * @return the value of role.invoice_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getInvoiceCreate() {
        return invoiceCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.invoice_create
     *
     * @param invoiceCreate the value for role.invoice_create
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setInvoiceCreate(Boolean invoiceCreate) {
        this.invoiceCreate = invoiceCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.pr_view_scope
     *
     * @return the value of role.pr_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public String getPrViewScope() {
        return prViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.pr_view_scope
     *
     * @param prViewScope the value for role.pr_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setPrViewScope(String prViewScope) {
        this.prViewScope = prViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.po_view_scope
     *
     * @return the value of role.po_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public String getPoViewScope() {
        return poViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.po_view_scope
     *
     * @param poViewScope the value for role.po_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setPoViewScope(String poViewScope) {
        this.poViewScope = poViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.receipt_view_scope
     *
     * @return the value of role.receipt_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public String getReceiptViewScope() {
        return receiptViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.receipt_view_scope
     *
     * @param receiptViewScope the value for role.receipt_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setReceiptViewScope(String receiptViewScope) {
        this.receiptViewScope = receiptViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.invoice_view_scope
     *
     * @return the value of role.invoice_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public String getInvoiceViewScope() {
        return invoiceViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.invoice_view_scope
     *
     * @param invoiceViewScope the value for role.invoice_view_scope
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setInvoiceViewScope(String invoiceViewScope) {
        this.invoiceViewScope = invoiceViewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.pr_approve
     *
     * @return the value of role.pr_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getPrApprove() {
        return prApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.pr_approve
     *
     * @param prApprove the value for role.pr_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setPrApprove(Boolean prApprove) {
        this.prApprove = prApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.po_approve
     *
     * @return the value of role.po_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getPoApprove() {
        return poApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.po_approve
     *
     * @param poApprove the value for role.po_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setPoApprove(Boolean poApprove) {
        this.poApprove = poApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.invoice_approve
     *
     * @return the value of role.invoice_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getInvoiceApprove() {
        return invoiceApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.invoice_approve
     *
     * @param invoiceApprove the value for role.invoice_approve
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setInvoiceApprove(Boolean invoiceApprove) {
        this.invoiceApprove = invoiceApprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.setting_manage
     *
     * @return the value of role.setting_manage
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public Boolean getSettingManage() {
        return settingManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.setting_manage
     *
     * @param settingManage the value for role.setting_manage
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setSettingManage(Boolean settingManage) {
        this.settingManage = settingManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.created_at
     *
     * @return the value of role.created_at
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.created_at
     *
     * @param createdAt the value for role.created_at
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.updated_at
     *
     * @return the value of role.updated_at
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.updated_at
     *
     * @param updatedAt the value for role.updated_at
     *
     * @mbg.generated Thu Apr 16 14:07:23 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}