package com.example.p2p.entity;

import java.time.LocalDateTime;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supplier_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.email
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phone_number
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.postal_code
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.prefecture
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String prefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.city
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.street_address
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String streetAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.building_name
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String buildingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.payment_term_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private String paymentTermId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.is_active
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.created_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.updated_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supplier_id
     *
     * @return the value of supplier.supplier_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supplier_id
     *
     * @param supplierId the value for supplier.supplier_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email
     *
     * @return the value of supplier.email
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email
     *
     * @param email the value for supplier.email
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone_number
     *
     * @return the value of supplier.phone_number
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone_number
     *
     * @param phoneNumber the value for supplier.phone_number
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.postal_code
     *
     * @return the value of supplier.postal_code
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.postal_code
     *
     * @param postalCode the value for supplier.postal_code
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.prefecture
     *
     * @return the value of supplier.prefecture
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.prefecture
     *
     * @param prefecture the value for supplier.prefecture
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.city
     *
     * @return the value of supplier.city
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.city
     *
     * @param city the value for supplier.city
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.street_address
     *
     * @return the value of supplier.street_address
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.street_address
     *
     * @param streetAddress the value for supplier.street_address
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.building_name
     *
     * @return the value of supplier.building_name
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.building_name
     *
     * @param buildingName the value for supplier.building_name
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.payment_term_id
     *
     * @return the value of supplier.payment_term_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public String getPaymentTermId() {
        return paymentTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.payment_term_id
     *
     * @param paymentTermId the value for supplier.payment_term_id
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setPaymentTermId(String paymentTermId) {
        this.paymentTermId = paymentTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.is_active
     *
     * @return the value of supplier.is_active
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.is_active
     *
     * @param isActive the value for supplier.is_active
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.created_at
     *
     * @return the value of supplier.created_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.created_at
     *
     * @param createdAt the value for supplier.created_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.updated_at
     *
     * @return the value of supplier.updated_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.updated_at
     *
     * @param updatedAt the value for supplier.updated_at
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}