package com.example.p2p.entity;

import java.time.LocalDateTime;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_name
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.first_name
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.last_name_kana
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String lastNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.first_name_kana
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String firstNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password_hash
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.role_id
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_active
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_name
     *
     * @return the value of users.last_name
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_name
     *
     * @param lastName the value for users.last_name
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.first_name
     *
     * @return the value of users.first_name
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.first_name
     *
     * @param firstName the value for users.first_name
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.last_name_kana
     *
     * @return the value of users.last_name_kana
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getLastNameKana() {
        return lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.last_name_kana
     *
     * @param lastNameKana the value for users.last_name_kana
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.first_name_kana
     *
     * @return the value of users.first_name_kana
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getFirstNameKana() {
        return firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.first_name_kana
     *
     * @param firstNameKana the value for users.first_name_kana
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password_hash
     *
     * @return the value of users.password_hash
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password_hash
     *
     * @param passwordHash the value for users.password_hash
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.role_id
     *
     * @return the value of users.role_id
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.role_id
     *
     * @param roleId the value for users.role_id
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_active
     *
     * @return the value of users.is_active
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_active
     *
     * @param isActive the value for users.is_active
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}