package com.example.p2p.mapper;

import com.example.p2p.entity.ApprovalStep;
import com.example.p2p.entity.ApprovalStepExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApprovalStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    long countByExample(ApprovalStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int deleteByExample(ApprovalStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int deleteByPrimaryKey(String approvalStepId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int insert(ApprovalStep row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int insertSelective(ApprovalStep row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    List<ApprovalStep> selectByExample(ApprovalStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    ApprovalStep selectByPrimaryKey(String approvalStepId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int updateByExampleSelective(@Param("row") ApprovalStep row, @Param("example") ApprovalStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int updateByExample(@Param("row") ApprovalStep row, @Param("example") ApprovalStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int updateByPrimaryKeySelective(ApprovalStep row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step
     *
     * @mbg.generated Sat May 16 11:26:44 JST 2026
     */
    int updateByPrimaryKey(ApprovalStep row);
}