package com.example.p2p.mapper;

import com.example.p2p.entity.ApprovalWorkflow;
import com.example.p2p.entity.ApprovalWorkflowExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApprovalWorkflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    long countByExample(ApprovalWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int deleteByExample(ApprovalWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int deleteByPrimaryKey(String approvalWorkflowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int insert(ApprovalWorkflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int insertSelective(ApprovalWorkflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    List<ApprovalWorkflow> selectByExample(ApprovalWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    ApprovalWorkflow selectByPrimaryKey(String approvalWorkflowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByExampleSelective(@Param("row") ApprovalWorkflow row, @Param("example") ApprovalWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByExample(@Param("row") ApprovalWorkflow row, @Param("example") ApprovalWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByPrimaryKeySelective(ApprovalWorkflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_workflow
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByPrimaryKey(ApprovalWorkflow row);
}