package com.example.p2p.mapper;

import com.example.p2p.entity.ApprovalStepApprover;
import com.example.p2p.entity.ApprovalStepApproverExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApprovalStepApproverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    long countByExample(ApprovalStepApproverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int deleteByExample(ApprovalStepApproverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int deleteByPrimaryKey(String approvalStepApproverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int insert(ApprovalStepApprover row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int insertSelective(ApprovalStepApprover row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    List<ApprovalStepApprover> selectByExample(ApprovalStepApproverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    ApprovalStepApprover selectByPrimaryKey(String approvalStepApproverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByExampleSelective(@Param("row") ApprovalStepApprover row, @Param("example") ApprovalStepApproverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByExample(@Param("row") ApprovalStepApprover row, @Param("example") ApprovalStepApproverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByPrimaryKeySelective(ApprovalStepApprover row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_step_approver
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByPrimaryKey(ApprovalStepApprover row);
}