package com.example.p2p.mapper;

import com.example.p2p.entity.ApprovalTask;
import com.example.p2p.entity.ApprovalTaskExample;
import com.example.p2p.entity.ApprovalTaskKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ApprovalTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    long countByExample(ApprovalTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int deleteByExample(ApprovalTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int deleteByPrimaryKey(ApprovalTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int insert(ApprovalTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int insertSelective(ApprovalTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    List<ApprovalTask> selectByExample(ApprovalTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    ApprovalTask selectByPrimaryKey(ApprovalTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByExampleSelective(@Param("row") ApprovalTask row, @Param("example") ApprovalTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByExample(@Param("row") ApprovalTask row, @Param("example") ApprovalTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByPrimaryKeySelective(ApprovalTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_task
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByPrimaryKey(ApprovalTask row);
}