package com.example.p2p.mapper;

import com.example.p2p.entity.EmailChangeRequest;
import com.example.p2p.entity.EmailChangeRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmailChangeRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    long countByExample(EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int deleteByExample(EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int insert(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int insertSelective(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    List<EmailChangeRequest> selectByExample(EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    EmailChangeRequest selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByExampleSelective(@Param("row") EmailChangeRequest row, @Param("example") EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByExample(@Param("row") EmailChangeRequest row, @Param("example") EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByPrimaryKeySelective(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_change_request
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByPrimaryKey(EmailChangeRequest row);
}