package com.example.p2p.mapper;

import com.example.p2p.entity.Item;
import com.example.p2p.entity.ItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    long countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int insert(Item row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int insertSelective(Item row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    Item selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int updateByExampleSelective(@Param("row") Item row, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int updateByExample(@Param("row") Item row, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int updateByPrimaryKeySelective(Item row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Apr 25 17:51:00 JST 2026
     */
    int updateByPrimaryKey(Item row);
}