package com.example.p2p.mapper;

import com.example.p2p.entity.PaymentTerm;
import com.example.p2p.entity.PaymentTermExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PaymentTermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    long countByExample(PaymentTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int deleteByExample(PaymentTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int deleteByPrimaryKey(String paymentTermId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int insert(PaymentTerm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int insertSelective(PaymentTerm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    List<PaymentTerm> selectByExample(PaymentTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    PaymentTerm selectByPrimaryKey(String paymentTermId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int updateByExampleSelective(@Param("row") PaymentTerm row, @Param("example") PaymentTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int updateByExample(@Param("row") PaymentTerm row, @Param("example") PaymentTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int updateByPrimaryKeySelective(PaymentTerm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_term
     *
     * @mbg.generated Thu Apr 23 18:12:43 JST 2026
     */
    int updateByPrimaryKey(PaymentTerm row);
}