package com.example.p2p.mapper;

import com.example.p2p.entity.PurchaseRequest;
import com.example.p2p.entity.PurchaseRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    long countByExample(PurchaseRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int deleteByExample(PurchaseRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int deleteByPrimaryKey(String prId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int insert(PurchaseRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int insertSelective(PurchaseRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    List<PurchaseRequest> selectByExample(PurchaseRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    PurchaseRequest selectByPrimaryKey(String prId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int updateByExampleSelective(@Param("row") PurchaseRequest row, @Param("example") PurchaseRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int updateByExample(@Param("row") PurchaseRequest row, @Param("example") PurchaseRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int updateByPrimaryKeySelective(PurchaseRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request
     *
     * @mbg.generated Sun Apr 26 15:32:57 JST 2026
     */
    int updateByPrimaryKey(PurchaseRequest row);
}