package com.example.p2p.mapper;

import com.example.p2p.entity.PurchaseOrder;
import com.example.p2p.entity.PurchaseOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    long countByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int deleteByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int deleteByPrimaryKey(String poId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int insert(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int insertSelective(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    List<PurchaseOrder> selectByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    PurchaseOrder selectByPrimaryKey(String poId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByExampleSelective(@Param("row") PurchaseOrder row, @Param("example") PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByExample(@Param("row") PurchaseOrder row, @Param("example") PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByPrimaryKeySelective(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Fri Jun 19 21:46:11 JST 2026
     */
    int updateByPrimaryKey(PurchaseOrder row);
}