package com.example.p2p.mapper;

import com.example.p2p.entity.PurchaseOrderLineAllocation;
import com.example.p2p.entity.PurchaseOrderLineAllocationExample;
import com.example.p2p.entity.PurchaseOrderLineAllocationKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseOrderLineAllocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    long countByExample(PurchaseOrderLineAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int deleteByExample(PurchaseOrderLineAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int deleteByPrimaryKey(PurchaseOrderLineAllocationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int insert(PurchaseOrderLineAllocation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int insertSelective(PurchaseOrderLineAllocation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    List<PurchaseOrderLineAllocation> selectByExample(PurchaseOrderLineAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    PurchaseOrderLineAllocation selectByPrimaryKey(PurchaseOrderLineAllocationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByExampleSelective(@Param("row") PurchaseOrderLineAllocation row, @Param("example") PurchaseOrderLineAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByExample(@Param("row") PurchaseOrderLineAllocation row, @Param("example") PurchaseOrderLineAllocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByPrimaryKeySelective(PurchaseOrderLineAllocation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order_line_allocation
     *
     * @mbg.generated Sat Jul 18 16:56:03 JST 2026
     */
    int updateByPrimaryKey(PurchaseOrderLineAllocation row);
}