package com.example.p2p.mapper;

import com.example.p2p.entity.PurchaseRequestDetail;
import com.example.p2p.entity.PurchaseRequestDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseRequestDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    long countByExample(PurchaseRequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int deleteByExample(PurchaseRequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int deleteByPrimaryKey(String prDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int insert(PurchaseRequestDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int insertSelective(PurchaseRequestDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    List<PurchaseRequestDetail> selectByExample(PurchaseRequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    PurchaseRequestDetail selectByPrimaryKey(String prDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int updateByExampleSelective(@Param("row") PurchaseRequestDetail row, @Param("example") PurchaseRequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int updateByExample(@Param("row") PurchaseRequestDetail row, @Param("example") PurchaseRequestDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int updateByPrimaryKeySelective(PurchaseRequestDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_detail
     *
     * @mbg.generated Sat Jun 06 18:27:49 JST 2026
     */
    int updateByPrimaryKey(PurchaseRequestDetail row);
}