package com.example.p2p.mapper;

import com.example.p2p.entity.PurchaseRequestPurchaseOrder;
import com.example.p2p.entity.PurchaseRequestPurchaseOrderExample;
import com.example.p2p.entity.PurchaseRequestPurchaseOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseRequestPurchaseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    long countByExample(PurchaseRequestPurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int deleteByExample(PurchaseRequestPurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int deleteByPrimaryKey(PurchaseRequestPurchaseOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int insert(PurchaseRequestPurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int insertSelective(PurchaseRequestPurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    List<PurchaseRequestPurchaseOrder> selectByExample(PurchaseRequestPurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    PurchaseRequestPurchaseOrder selectByPrimaryKey(PurchaseRequestPurchaseOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int updateByExampleSelective(@Param("row") PurchaseRequestPurchaseOrder row, @Param("example") PurchaseRequestPurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int updateByExample(@Param("row") PurchaseRequestPurchaseOrder row, @Param("example") PurchaseRequestPurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int updateByPrimaryKeySelective(PurchaseRequestPurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_request_purchase_order
     *
     * @mbg.generated Thu Jun 18 21:51:16 JST 2026
     */
    int updateByPrimaryKey(PurchaseRequestPurchaseOrder row);
}