package com.example.p2p.mapper;

import com.example.p2p.entity.Supplier;
import com.example.p2p.entity.SupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    long countByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int deleteByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int deleteByPrimaryKey(String supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int insert(Supplier row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int insertSelective(Supplier row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    List<Supplier> selectByExample(SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    Supplier selectByPrimaryKey(String supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByExampleSelective(@Param("row") Supplier row, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByExample(@Param("row") Supplier row, @Param("example") SupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByPrimaryKeySelective(Supplier row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByPrimaryKey(Supplier row);
}