package com.example.p2p.mapper;

import com.example.p2p.entity.Unit;
import com.example.p2p.entity.UnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    long countByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int deleteByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int deleteByPrimaryKey(String unitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int insert(Unit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int insertSelective(Unit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    List<Unit> selectByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    Unit selectByPrimaryKey(String unitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByExampleSelective(@Param("row") Unit row, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByExample(@Param("row") Unit row, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByPrimaryKeySelective(Unit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Sun May 03 17:09:56 JST 2026
     */
    int updateByPrimaryKey(Unit row);
}