package com.example.p2p.mapper;

import com.example.p2p.entity.UserInvitationToken;
import com.example.p2p.entity.UserInvitationTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserInvitationTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    long countByExample(UserInvitationTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int deleteByExample(UserInvitationTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int insert(UserInvitationToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int insertSelective(UserInvitationToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    List<UserInvitationToken> selectByExample(UserInvitationTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    UserInvitationToken selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int updateByExampleSelective(@Param("row") UserInvitationToken row, @Param("example") UserInvitationTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int updateByExample(@Param("row") UserInvitationToken row, @Param("example") UserInvitationTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int updateByPrimaryKeySelective(UserInvitationToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_invitation_token
     *
     * @mbg.generated Mon Jun 29 16:10:46 JST 2026
     */
    int updateByPrimaryKey(UserInvitationToken row);
}